"""add expiry reminder flags

Revision ID: 317e2da95c63
Revises: dedf34a72c49
Create Date: 2026-09-01 10:45:17.344275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317e2da95c63'
down_revision: Union[str, Sequence[str], None] = 'dedf34a72c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('reminder_2_days_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('reminder_1_day_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'reminder_1_day_sent')
    op.drop_column('customers', 'reminder_2_days_sent')
    # ### end Alembic commands ###
