"""add marketing_speed to plans

Revision ID: 3daf80649c27
Revises: fba08404cafa
Create Date: 2026-08-06 07:18:16.127143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3daf80649c27'
down_revision: Union[str, Sequence[str], None] = 'fba08404cafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('marketing_speed', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'marketing_speed')
    # ### end Alembic commands ###
