"""add pay_token to customers

Revision ID: fba08404cafa
Revises: a0eec7e00e41
Create Date: 2026-08-06 06:25:38.029888

"""
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba08404cafa'
down_revision: Union[str, Sequence[str], None] = 'a0eec7e00e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('customers', sa.Column('pay_token', sa.String(length=32), nullable=True))

    connection = op.get_bind()
    customers = connection.execute(sa.text('SELECT id FROM customers')).fetchall()
    for (customer_id,) in customers:
        connection.execute(
            sa.text('UPDATE customers SET pay_token = :token WHERE id = :id'),
            {'token': secrets.token_hex(16), 'id': customer_id},
        )

    op.alter_column('customers', 'pay_token', nullable=False)
    op.create_unique_constraint(None, 'customers', ['pay_token'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'pay_token')
    # ### end Alembic commands ###
